### ISSUE TITLE
Missing sofort logo for DIB

### ISSUE THREAD

**Issue by floriankisser** [datatrans/payment-logos#29]
Lightbox and the admin interface use a sofort logo not present neither in this repo nor in https://docs.datatrans.ch/docs/payment-methods#klarna.

**Comment by floriankisser** [comment]
I see that they have been removed in https://github.com/datatrans/payment-logos/commit/46275e7ac97795ad1188a8d6812eea10f74853ee, does that mean the documentation is up-to-date, but e.g. lightbox is not?

**Comment by pstadler** [comment]
We're still clarifying the situation. It could be that we cannot add _Sofort_ logos to this repository here.
Handing this over to @richiehug

**Comment by richiehug** [comment]
Hey @floriankisser! We use some logos at Datatrans that are not part of this repo, e.g., the Sofort logo. This is correct, as Klarna wants its brand to be more visible than its sub-brands. The hosted payment pages and the merchant portal will continue to use these sub-brand logos. I hope this clarifies your question/doubt regarding the inconsistency of payment logos in this repo vs. our payment interfaces!
